version: "3.1"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./migration/docker-database-init.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"